Repository CrowCpp/Crow, pull requests merged in 2024-03, with the labels that each got.

#763 Call middleware during upgrade request
  include/crow/http_connection.h
Labels: bug

#772 Update doxygen-gh-pages.yml, added mike for versioning
  .github/workflows/doxygen-gh-pages.yml
Labels: task

#769 Create dependabot.yml
  .github/dependabot.yml
Labels: task

#748 Add indentation to json dump method
  include/crow/json.h
  tests/unittest.cpp
Labels: feature
